from PyQt5 import QtCore, QtGui, QtWidgets
from experience_calc import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Pokemon Level Sim")
        MainWindow.resize(318, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 240, 281, 41))
        self.pushButton.setObjectName("pushButton")
        self.route = QtWidgets.QComboBox(self.centralwidget)
        self.route.setGeometry(QtCore.QRect(20, 10, 281, 31))
        self.route.setObjectName("route")
        self.route.addItem("")
        self.route.addItem("")
        self.pokemon = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon.setGeometry(QtCore.QRect(20, 130, 281, 31))
        self.pokemon.setObjectName("pokemon")
        list1 = [""]*808
        self.pokemon.addItems(list1)
        self.tradestatus = QtWidgets.QComboBox(self.centralwidget)
        self.tradestatus.setGeometry(QtCore.QRect(20, 100, 281, 31))
        self.tradestatus.setObjectName("tradestatus")
        self.tradestatus.addItem("")
        self.tradestatus.addItem("")
        self.tradestatus.addItem("")
        self.tradestatus.addItem("")
        self.affection = QtWidgets.QComboBox(self.centralwidget)
        self.affection.setGeometry(QtCore.QRect(20, 70, 281, 31))
        self.affection.setObjectName("affection")
        self.affection.addItem("")
        self.affection.addItem("")
        self.affection.addItem("")
        self.luckyegg = QtWidgets.QComboBox(self.centralwidget)
        self.luckyegg.setGeometry(QtCore.QRect(20, 40, 281, 31))
        self.luckyegg.setObjectName("luckyegg")
        self.luckyegg.addItem("")
        self.luckyegg.addItem("")
        self.luckyegg.addItem("")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 169, 71, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 209, 51, 16))
        self.label_2.setObjectName("label_2")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 318, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.button)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.level = QtWidgets.QSpinBox(self.centralwidget)
        self.level.setGeometry(QtCore.QRect(170, 169, 42, 31))
        self.level.setAccelerated(True)
        self.level.setMinimum(1)
        self.level.setMaximum(100)
        self.level.setObjectName("level")
        self.level_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.level_2.setGeometry(QtCore.QRect(170, 200, 42, 31))
        self.level_2.setAccelerated(True)
        self.level_2.setMinimum(1)
        self.level_2.setMaximum(100)
        self.level_2.setObjectName("level_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

    def retranslateUi(self, MainWindow):
    
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pokemon Level Sim"))
        self.pushButton.setText(_translate("MainWindow", "All Options Set"))
        self.route.setCurrentText(_translate("MainWindow", "Select a Route"))
        self.route.setItemText(0, _translate("MainWindow", "Select a Route"))
        self.route.setItemText(1, _translate("MainWindow", "(Alola) Route One"))
        self.pokemon.setItemText(0, _translate("MainWindow", "Select Pokemon"))
        self.pokemon.setItemText(1, _translate("MainWindow", "Bulbasaur"))
        self.pokemon.setItemText(2, _translate("MainWindow", "Ivysaur"))
        self.pokemon.setItemText(3, _translate("MainWindow", "Venusaur"))
        self.pokemon.setItemText(4, _translate("MainWindow", "Charmander"))
        self.pokemon.setItemText(5, _translate("MainWindow", "Charmeleon"))
        self.pokemon.setItemText(6, _translate("MainWindow", "Charizard"))
        self.pokemon.setItemText(7, _translate("MainWindow", "Squirtle"))
        self.pokemon.setItemText(8, _translate("MainWindow", "Wartortle"))
        self.pokemon.setItemText(9, _translate("MainWindow", "Blastoise"))
        self.pokemon.setItemText(10, _translate("MainWindow", "Caterpie"))
        self.pokemon.setItemText(11, _translate("MainWindow", "Metapod"))
        self.pokemon.setItemText(12, _translate("MainWindow", "Butterfree"))
        self.pokemon.setItemText(13, _translate("MainWindow", "Weedle"))
        self.pokemon.setItemText(14, _translate("MainWindow", "Kakuna"))
        self.pokemon.setItemText(15, _translate("MainWindow", "Beedrill"))
        self.pokemon.setItemText(16, _translate("MainWindow", "Pidgey"))
        self.pokemon.setItemText(17, _translate("MainWindow", "Pidgeotto"))
        self.pokemon.setItemText(18, _translate("MainWindow", "Pidgeot"))
        self.pokemon.setItemText(19, _translate("MainWindow", "Rattata"))
        self.pokemon.setItemText(20, _translate("MainWindow", "Raticate"))
        self.pokemon.setItemText(21, _translate("MainWindow", "Spearow"))
        self.pokemon.setItemText(22, _translate("MainWindow", "Fearow"))
        self.pokemon.setItemText(23, _translate("MainWindow", "Ekans"))
        self.pokemon.setItemText(24, _translate("MainWindow", "Arbok"))
        self.pokemon.setItemText(25, _translate("MainWindow", "Pikachu"))
        self.pokemon.setItemText(26, _translate("MainWindow", "Raichu"))
        self.pokemon.setItemText(27, _translate("MainWindow", "Sandshrew"))
        self.pokemon.setItemText(28, _translate("MainWindow", "Sandslash"))
        self.pokemon.setItemText(29, _translate("MainWindow", "Nidoran♀"))
        self.pokemon.setItemText(30, _translate("MainWindow", "Nidorina"))
        self.pokemon.setItemText(31, _translate("MainWindow", "Nidoqueen"))
        self.pokemon.setItemText(32, _translate("MainWindow", "Nidoran♂"))
        self.pokemon.setItemText(33, _translate("MainWindow", "Nidorino"))
        self.pokemon.setItemText(34, _translate("MainWindow", "Nidoking"))
        self.pokemon.setItemText(35, _translate("MainWindow", "Clefairy"))
        self.pokemon.setItemText(36, _translate("MainWindow", "Clefable"))
        self.pokemon.setItemText(37, _translate("MainWindow", "Vulpix"))
        self.pokemon.setItemText(38, _translate("MainWindow", "Ninetales"))
        self.pokemon.setItemText(39, _translate("MainWindow", "Jigglypuff"))
        self.pokemon.setItemText(40, _translate("MainWindow", "Wigglytuff"))
        self.pokemon.setItemText(41, _translate("MainWindow", "Zubat"))
        self.pokemon.setItemText(42, _translate("MainWindow", "Golbat"))
        self.pokemon.setItemText(43, _translate("MainWindow", "Oddish"))
        self.pokemon.setItemText(44, _translate("MainWindow", "Gloom"))
        self.pokemon.setItemText(45, _translate("MainWindow", "Vileplume"))
        self.pokemon.setItemText(46, _translate("MainWindow", "Paras"))
        self.pokemon.setItemText(47, _translate("MainWindow", "Parasect"))
        self.pokemon.setItemText(48, _translate("MainWindow", "Venonat"))
        self.pokemon.setItemText(49, _translate("MainWindow", "Venomoth"))
        self.pokemon.setItemText(50, _translate("MainWindow", "Diglett"))
        self.pokemon.setItemText(51, _translate("MainWindow", "Dugtrio"))
        self.pokemon.setItemText(52, _translate("MainWindow", "Meowth"))
        self.pokemon.setItemText(53, _translate("MainWindow", "Persian"))
        self.pokemon.setItemText(54, _translate("MainWindow", "Psyduck"))
        self.pokemon.setItemText(55, _translate("MainWindow", "Golduck"))
        self.pokemon.setItemText(56, _translate("MainWindow", "Mankey"))
        self.pokemon.setItemText(57, _translate("MainWindow", "Primeape"))
        self.pokemon.setItemText(58, _translate("MainWindow", "Growlithe"))
        self.pokemon.setItemText(59, _translate("MainWindow", "Arcanine"))
        self.pokemon.setItemText(60, _translate("MainWindow", "Poliwag"))
        self.pokemon.setItemText(61, _translate("MainWindow", "Poliwhirl"))
        self.pokemon.setItemText(62, _translate("MainWindow", "Poliwrath"))
        self.pokemon.setItemText(63, _translate("MainWindow", "Abra"))
        self.pokemon.setItemText(64, _translate("MainWindow", "Kadabra"))
        self.pokemon.setItemText(65, _translate("MainWindow", "Alakazam"))
        self.pokemon.setItemText(66, _translate("MainWindow", "Machop"))
        self.pokemon.setItemText(67, _translate("MainWindow", "Machoke"))
        self.pokemon.setItemText(68, _translate("MainWindow", "Machamp"))
        self.pokemon.setItemText(69, _translate("MainWindow", "Bellsprout"))
        self.pokemon.setItemText(70, _translate("MainWindow", "Weepinbell"))
        self.pokemon.setItemText(71, _translate("MainWindow", "Victreebel"))
        self.pokemon.setItemText(72, _translate("MainWindow", "Tentacool"))
        self.pokemon.setItemText(73, _translate("MainWindow", "Tentacruel"))
        self.pokemon.setItemText(74, _translate("MainWindow", "Geodude"))
        self.pokemon.setItemText(75, _translate("MainWindow", "Graveler"))
        self.pokemon.setItemText(76, _translate("MainWindow", "Golem"))
        self.pokemon.setItemText(77, _translate("MainWindow", "Ponyta"))
        self.pokemon.setItemText(78, _translate("MainWindow", "Rapidash"))
        self.pokemon.setItemText(79, _translate("MainWindow", "Slowpoke"))
        self.pokemon.setItemText(80, _translate("MainWindow", "Slowbro"))
        self.pokemon.setItemText(81, _translate("MainWindow", "Magnemite"))
        self.pokemon.setItemText(82, _translate("MainWindow", "Magneton"))
        self.pokemon.setItemText(83, _translate("MainWindow", "Farfetch’d"))
        self.pokemon.setItemText(84, _translate("MainWindow", "Doduo"))
        self.pokemon.setItemText(85, _translate("MainWindow", "Dodrio"))
        self.pokemon.setItemText(86, _translate("MainWindow", "Seel"))
        self.pokemon.setItemText(87, _translate("MainWindow", "Dewgong"))
        self.pokemon.setItemText(88, _translate("MainWindow", "Grimer"))
        self.pokemon.setItemText(89, _translate("MainWindow", "Muk"))
        self.pokemon.setItemText(90, _translate("MainWindow", "Shellder"))
        self.pokemon.setItemText(91, _translate("MainWindow", "Cloyster"))
        self.pokemon.setItemText(92, _translate("MainWindow", "Gastly"))
        self.pokemon.setItemText(93, _translate("MainWindow", "Haunter"))
        self.pokemon.setItemText(94, _translate("MainWindow", "Gengar"))
        self.pokemon.setItemText(95, _translate("MainWindow", "Onix"))
        self.pokemon.setItemText(96, _translate("MainWindow", "Drowzee"))
        self.pokemon.setItemText(97, _translate("MainWindow", "Hypno"))
        self.pokemon.setItemText(98, _translate("MainWindow", "Krabby"))
        self.pokemon.setItemText(99, _translate("MainWindow", "Kingler"))
        self.pokemon.setItemText(100, _translate("MainWindow", "Voltorb"))
        self.pokemon.setItemText(101, _translate("MainWindow", "Electrode"))
        self.pokemon.setItemText(102, _translate("MainWindow", "Exeggcute"))
        self.pokemon.setItemText(103, _translate("MainWindow", "Exeggutor"))
        self.pokemon.setItemText(104, _translate("MainWindow", "Cubone"))
        self.pokemon.setItemText(105, _translate("MainWindow", "Marowak"))
        self.pokemon.setItemText(106, _translate("MainWindow", "Hitmonlee"))
        self.pokemon.setItemText(107, _translate("MainWindow", "Hitmonchan"))
        self.pokemon.setItemText(108, _translate("MainWindow", "Lickitung"))
        self.pokemon.setItemText(109, _translate("MainWindow", "Koffing"))
        self.pokemon.setItemText(110, _translate("MainWindow", "Weezing"))
        self.pokemon.setItemText(111, _translate("MainWindow", "Rhyhorn"))
        self.pokemon.setItemText(112, _translate("MainWindow", "Rhydon"))
        self.pokemon.setItemText(113, _translate("MainWindow", "Chansey"))
        self.pokemon.setItemText(114, _translate("MainWindow", "Tangela"))
        self.pokemon.setItemText(115, _translate("MainWindow", "Kangaskhan"))
        self.pokemon.setItemText(116, _translate("MainWindow", "Horsea"))
        self.pokemon.setItemText(117, _translate("MainWindow", "Seadra"))
        self.pokemon.setItemText(118, _translate("MainWindow", "Goldeen"))
        self.pokemon.setItemText(119, _translate("MainWindow", "Seaking"))
        self.pokemon.setItemText(120, _translate("MainWindow", "Staryu"))
        self.pokemon.setItemText(121, _translate("MainWindow", "Starmie"))
        self.pokemon.setItemText(122, _translate("MainWindow", "Mr. Mime"))
        self.pokemon.setItemText(123, _translate("MainWindow", "Scyther"))
        self.pokemon.setItemText(124, _translate("MainWindow", "Jynx"))
        self.pokemon.setItemText(125, _translate("MainWindow", "Electabuzz"))
        self.pokemon.setItemText(126, _translate("MainWindow", "Magmar"))
        self.pokemon.setItemText(127, _translate("MainWindow", "Pinsir"))
        self.pokemon.setItemText(128, _translate("MainWindow", "Tauros"))
        self.pokemon.setItemText(129, _translate("MainWindow", "Magikarp"))
        self.pokemon.setItemText(130, _translate("MainWindow", "Gyarados"))
        self.pokemon.setItemText(131, _translate("MainWindow", "Lapras"))
        self.pokemon.setItemText(132, _translate("MainWindow", "Ditto"))
        self.pokemon.setItemText(133, _translate("MainWindow", "Eevee"))
        self.pokemon.setItemText(134, _translate("MainWindow", "Vaporeon"))
        self.pokemon.setItemText(135, _translate("MainWindow", "Jolteon"))
        self.pokemon.setItemText(136, _translate("MainWindow", "Flareon"))
        self.pokemon.setItemText(137, _translate("MainWindow", "Porygon"))
        self.pokemon.setItemText(138, _translate("MainWindow", "Omanyte"))
        self.pokemon.setItemText(139, _translate("MainWindow", "Omastar"))
        self.pokemon.setItemText(140, _translate("MainWindow", "Kabuto"))
        self.pokemon.setItemText(141, _translate("MainWindow", "Kabutops"))
        self.pokemon.setItemText(142, _translate("MainWindow", "Aerodactyl"))
        self.pokemon.setItemText(143, _translate("MainWindow", "Snorlax"))
        self.pokemon.setItemText(144, _translate("MainWindow", "Articuno"))
        self.pokemon.setItemText(145, _translate("MainWindow", "Zapdos"))
        self.pokemon.setItemText(146, _translate("MainWindow", "Moltres"))
        self.pokemon.setItemText(147, _translate("MainWindow", "Dratini"))
        self.pokemon.setItemText(148, _translate("MainWindow", "Dragonair"))
        self.pokemon.setItemText(149, _translate("MainWindow", "Dragonite"))
        self.pokemon.setItemText(150, _translate("MainWindow", "Mewtwo"))
        self.pokemon.setItemText(151, _translate("MainWindow", "Mew"))
        self.pokemon.setItemText(152, _translate("MainWindow", "Chikorita"))
        self.pokemon.setItemText(153, _translate("MainWindow", "Bayleef"))
        self.pokemon.setItemText(154, _translate("MainWindow", "Meganium"))
        self.pokemon.setItemText(155, _translate("MainWindow", "Cyndaquil"))
        self.pokemon.setItemText(156, _translate("MainWindow", "Quilava"))
        self.pokemon.setItemText(157, _translate("MainWindow", "Typhlosion"))
        self.pokemon.setItemText(158, _translate("MainWindow", "Totodile"))
        self.pokemon.setItemText(159, _translate("MainWindow", "Croconaw"))
        self.pokemon.setItemText(160, _translate("MainWindow", "Feraligatr"))
        self.pokemon.setItemText(161, _translate("MainWindow", "Sentret"))
        self.pokemon.setItemText(162, _translate("MainWindow", "Furret"))
        self.pokemon.setItemText(163, _translate("MainWindow", "Hoothoot"))
        self.pokemon.setItemText(164, _translate("MainWindow", "Noctowl"))
        self.pokemon.setItemText(165, _translate("MainWindow", "Ledyba"))
        self.pokemon.setItemText(166, _translate("MainWindow", "Ledian"))
        self.pokemon.setItemText(167, _translate("MainWindow", "Spinarak"))
        self.pokemon.setItemText(168, _translate("MainWindow", "Ariados"))
        self.pokemon.setItemText(169, _translate("MainWindow", "Crobat"))
        self.pokemon.setItemText(170, _translate("MainWindow", "Chinchou"))
        self.pokemon.setItemText(171, _translate("MainWindow", "Lanturn"))
        self.pokemon.setItemText(172, _translate("MainWindow", "Pichu"))
        self.pokemon.setItemText(173, _translate("MainWindow", "Cleffa"))
        self.pokemon.setItemText(174, _translate("MainWindow", "Igglybuff"))
        self.pokemon.setItemText(175, _translate("MainWindow", "Togepi"))
        self.pokemon.setItemText(176, _translate("MainWindow", "Togetic"))
        self.pokemon.setItemText(177, _translate("MainWindow", "Natu"))
        self.pokemon.setItemText(178, _translate("MainWindow", "Xatu"))
        self.pokemon.setItemText(179, _translate("MainWindow", "Mareep"))
        self.pokemon.setItemText(180, _translate("MainWindow", "Flaaffy"))
        self.pokemon.setItemText(181, _translate("MainWindow", "Ampharos"))
        self.pokemon.setItemText(182, _translate("MainWindow", "Bellossom"))
        self.pokemon.setItemText(183, _translate("MainWindow", "Marill"))
        self.pokemon.setItemText(184, _translate("MainWindow", "Azumarill"))
        self.pokemon.setItemText(185, _translate("MainWindow", "Sudowoodo"))
        self.pokemon.setItemText(186, _translate("MainWindow", "Politoed"))
        self.pokemon.setItemText(187, _translate("MainWindow", "Hoppip"))
        self.pokemon.setItemText(188, _translate("MainWindow", "Skiploom"))
        self.pokemon.setItemText(189, _translate("MainWindow", "Jumpluff"))
        self.pokemon.setItemText(190, _translate("MainWindow", "Aipom"))
        self.pokemon.setItemText(191, _translate("MainWindow", "Sunkern"))
        self.pokemon.setItemText(192, _translate("MainWindow", "Sunflora"))
        self.pokemon.setItemText(193, _translate("MainWindow", "Yanma"))
        self.pokemon.setItemText(194, _translate("MainWindow", "Wooper"))
        self.pokemon.setItemText(195, _translate("MainWindow", "Quagsire"))
        self.pokemon.setItemText(196, _translate("MainWindow", "Espeon"))
        self.pokemon.setItemText(197, _translate("MainWindow", "Umbreon"))
        self.pokemon.setItemText(198, _translate("MainWindow", "Murkrow"))
        self.pokemon.setItemText(199, _translate("MainWindow", "Slowking"))
        self.pokemon.setItemText(200, _translate("MainWindow", "Misdreavus"))
        self.pokemon.setItemText(201, _translate("MainWindow", "Unown"))
        self.pokemon.setItemText(202, _translate("MainWindow", "Wobbuffet"))
        self.pokemon.setItemText(203, _translate("MainWindow", "Girafarig"))
        self.pokemon.setItemText(204, _translate("MainWindow", "Pineco"))
        self.pokemon.setItemText(205, _translate("MainWindow", "Forretress"))
        self.pokemon.setItemText(206, _translate("MainWindow", "Dunsparce"))
        self.pokemon.setItemText(207, _translate("MainWindow", "Gligar"))
        self.pokemon.setItemText(208, _translate("MainWindow", "Steelix"))
        self.pokemon.setItemText(209, _translate("MainWindow", "Snubbull"))
        self.pokemon.setItemText(210, _translate("MainWindow", "Granbull"))
        self.pokemon.setItemText(211, _translate("MainWindow", "Qwilfish"))
        self.pokemon.setItemText(212, _translate("MainWindow", "Scizor"))
        self.pokemon.setItemText(213, _translate("MainWindow", "Shuckle"))
        self.pokemon.setItemText(214, _translate("MainWindow", "Heracross"))
        self.pokemon.setItemText(215, _translate("MainWindow", "Sneasel"))
        self.pokemon.setItemText(216, _translate("MainWindow", "Teddiursa"))
        self.pokemon.setItemText(217, _translate("MainWindow", "Ursaring"))
        self.pokemon.setItemText(218, _translate("MainWindow", "Slugma"))
        self.pokemon.setItemText(219, _translate("MainWindow", "Magcargo"))
        self.pokemon.setItemText(220, _translate("MainWindow", "Swinub"))
        self.pokemon.setItemText(221, _translate("MainWindow", "Piloswine"))
        self.pokemon.setItemText(222, _translate("MainWindow", "Corsola"))
        self.pokemon.setItemText(223, _translate("MainWindow", "Remoraid"))
        self.pokemon.setItemText(224, _translate("MainWindow", "Octillery"))
        self.pokemon.setItemText(225, _translate("MainWindow", "Delibird"))
        self.pokemon.setItemText(226, _translate("MainWindow", "Mantine"))
        self.pokemon.setItemText(227, _translate("MainWindow", "Skarmory"))
        self.pokemon.setItemText(228, _translate("MainWindow", "Houndour"))
        self.pokemon.setItemText(229, _translate("MainWindow", "Houndoom"))
        self.pokemon.setItemText(230, _translate("MainWindow", "Kingdra"))
        self.pokemon.setItemText(231, _translate("MainWindow", "Phanpy"))
        self.pokemon.setItemText(232, _translate("MainWindow", "Donphan"))
        self.pokemon.setItemText(233, _translate("MainWindow", "Porygon2"))
        self.pokemon.setItemText(234, _translate("MainWindow", "Stantler"))
        self.pokemon.setItemText(235, _translate("MainWindow", "Smeargle"))
        self.pokemon.setItemText(236, _translate("MainWindow", "Tyrogue"))
        self.pokemon.setItemText(237, _translate("MainWindow", "Hitmontop"))
        self.pokemon.setItemText(238, _translate("MainWindow", "Smoochum"))
        self.pokemon.setItemText(239, _translate("MainWindow", "Elekid"))
        self.pokemon.setItemText(240, _translate("MainWindow", "Magby"))
        self.pokemon.setItemText(241, _translate("MainWindow", "Miltank"))
        self.pokemon.setItemText(242, _translate("MainWindow", "Blissey"))
        self.pokemon.setItemText(243, _translate("MainWindow", "Raikou"))
        self.pokemon.setItemText(244, _translate("MainWindow", "Entei"))
        self.pokemon.setItemText(245, _translate("MainWindow", "Suicune"))
        self.pokemon.setItemText(246, _translate("MainWindow", "Larvitar"))
        self.pokemon.setItemText(247, _translate("MainWindow", "Pupitar"))
        self.pokemon.setItemText(248, _translate("MainWindow", "Tyranitar"))
        self.pokemon.setItemText(249, _translate("MainWindow", "Lugia"))
        self.pokemon.setItemText(250, _translate("MainWindow", "Ho-Oh"))
        self.pokemon.setItemText(251, _translate("MainWindow", "Celebi"))
        self.pokemon.setItemText(252, _translate("MainWindow", "Treecko"))
        self.pokemon.setItemText(253, _translate("MainWindow", "Grovyle"))
        self.pokemon.setItemText(254, _translate("MainWindow", "Sceptile"))
        self.pokemon.setItemText(255, _translate("MainWindow", "Torchic"))
        self.pokemon.setItemText(256, _translate("MainWindow", "Combusken"))
        self.pokemon.setItemText(257, _translate("MainWindow", "Blaziken"))
        self.pokemon.setItemText(258, _translate("MainWindow", "Mudkip"))
        self.pokemon.setItemText(259, _translate("MainWindow", "Marshtomp"))
        self.pokemon.setItemText(260, _translate("MainWindow", "Swampert"))
        self.pokemon.setItemText(261, _translate("MainWindow", "Poochyena"))
        self.pokemon.setItemText(262, _translate("MainWindow", "Mightyena"))
        self.pokemon.setItemText(263, _translate("MainWindow", "Zigzagoon"))
        self.pokemon.setItemText(264, _translate("MainWindow", "Linoone"))
        self.pokemon.setItemText(265, _translate("MainWindow", "Wurmple"))
        self.pokemon.setItemText(266, _translate("MainWindow", "Silcoon"))
        self.pokemon.setItemText(267, _translate("MainWindow", "Beautifly"))
        self.pokemon.setItemText(268, _translate("MainWindow", "Cascoon"))
        self.pokemon.setItemText(269, _translate("MainWindow", "Dustox"))
        self.pokemon.setItemText(270, _translate("MainWindow", "Lotad"))
        self.pokemon.setItemText(271, _translate("MainWindow", "Lombre"))
        self.pokemon.setItemText(272, _translate("MainWindow", "Ludicolo"))
        self.pokemon.setItemText(273, _translate("MainWindow", "Seedot"))
        self.pokemon.setItemText(274, _translate("MainWindow", "Nuzleaf"))
        self.pokemon.setItemText(275, _translate("MainWindow", "Shiftry"))
        self.pokemon.setItemText(276, _translate("MainWindow", "Taillow"))
        self.pokemon.setItemText(277, _translate("MainWindow", "Swellow"))
        self.pokemon.setItemText(278, _translate("MainWindow", "Wingull"))
        self.pokemon.setItemText(279, _translate("MainWindow", "Pelipper"))
        self.pokemon.setItemText(280, _translate("MainWindow", "Ralts"))
        self.pokemon.setItemText(281, _translate("MainWindow", "Kirlia"))
        self.pokemon.setItemText(282, _translate("MainWindow", "Gardevoir"))
        self.pokemon.setItemText(283, _translate("MainWindow", "Surskit"))
        self.pokemon.setItemText(284, _translate("MainWindow", "Masquerain"))
        self.pokemon.setItemText(285, _translate("MainWindow", "Shroomish"))
        self.pokemon.setItemText(286, _translate("MainWindow", "Breloom"))
        self.pokemon.setItemText(287, _translate("MainWindow", "Slakoth"))
        self.pokemon.setItemText(288, _translate("MainWindow", "Vigoroth"))
        self.pokemon.setItemText(289, _translate("MainWindow", "Slaking"))
        self.pokemon.setItemText(290, _translate("MainWindow", "Nincada"))
        self.pokemon.setItemText(291, _translate("MainWindow", "Ninjask"))
        self.pokemon.setItemText(292, _translate("MainWindow", "Shedinja"))
        self.pokemon.setItemText(293, _translate("MainWindow", "Whismur"))
        self.pokemon.setItemText(294, _translate("MainWindow", "Loudred"))
        self.pokemon.setItemText(295, _translate("MainWindow", "Exploud"))
        self.pokemon.setItemText(296, _translate("MainWindow", "Makuhita"))
        self.pokemon.setItemText(297, _translate("MainWindow", "Hariyama"))
        self.pokemon.setItemText(298, _translate("MainWindow", "Azurill"))
        self.pokemon.setItemText(299, _translate("MainWindow", "Nosepass"))
        self.pokemon.setItemText(300, _translate("MainWindow", "Skitty"))
        self.pokemon.setItemText(301, _translate("MainWindow", "Delcatty"))
        self.pokemon.setItemText(302, _translate("MainWindow", "Sableye"))
        self.pokemon.setItemText(303, _translate("MainWindow", "Mawile"))
        self.pokemon.setItemText(304, _translate("MainWindow", "Aron"))
        self.pokemon.setItemText(305, _translate("MainWindow", "Lairon"))
        self.pokemon.setItemText(306, _translate("MainWindow", "Aggron"))
        self.pokemon.setItemText(307, _translate("MainWindow", "Meditite"))
        self.pokemon.setItemText(308, _translate("MainWindow", "Medicham"))
        self.pokemon.setItemText(309, _translate("MainWindow", "Electrike"))
        self.pokemon.setItemText(310, _translate("MainWindow", "Manectric"))
        self.pokemon.setItemText(311, _translate("MainWindow", "Plusle"))
        self.pokemon.setItemText(312, _translate("MainWindow", "Minun"))
        self.pokemon.setItemText(313, _translate("MainWindow", "Volbeat"))
        self.pokemon.setItemText(314, _translate("MainWindow", "Illumise"))
        self.pokemon.setItemText(315, _translate("MainWindow", "Roselia"))
        self.pokemon.setItemText(316, _translate("MainWindow", "Gulpin"))
        self.pokemon.setItemText(317, _translate("MainWindow", "Swalot"))
        self.pokemon.setItemText(318, _translate("MainWindow", "Carvanha"))
        self.pokemon.setItemText(319, _translate("MainWindow", "Sharpedo"))
        self.pokemon.setItemText(320, _translate("MainWindow", "Wailmer"))
        self.pokemon.setItemText(321, _translate("MainWindow", "Wailord"))
        self.pokemon.setItemText(322, _translate("MainWindow", "Numel"))
        self.pokemon.setItemText(323, _translate("MainWindow", "Camerupt"))
        self.pokemon.setItemText(324, _translate("MainWindow", "Torkoal"))
        self.pokemon.setItemText(325, _translate("MainWindow", "Spoink"))
        self.pokemon.setItemText(326, _translate("MainWindow", "Grumpig"))
        self.pokemon.setItemText(327, _translate("MainWindow", "Spinda"))
        self.pokemon.setItemText(328, _translate("MainWindow", "Trapinch"))
        self.pokemon.setItemText(329, _translate("MainWindow", "Vibrava"))
        self.pokemon.setItemText(330, _translate("MainWindow", "Flygon"))
        self.pokemon.setItemText(331, _translate("MainWindow", "Cacnea"))
        self.pokemon.setItemText(332, _translate("MainWindow", "Cacturne"))
        self.pokemon.setItemText(333, _translate("MainWindow", "Swablu"))
        self.pokemon.setItemText(334, _translate("MainWindow", "Altaria"))
        self.pokemon.setItemText(335, _translate("MainWindow", "Zangoose"))
        self.pokemon.setItemText(336, _translate("MainWindow", "Seviper"))
        self.pokemon.setItemText(337, _translate("MainWindow", "Lunatone"))
        self.pokemon.setItemText(338, _translate("MainWindow", "Solrock"))
        self.pokemon.setItemText(339, _translate("MainWindow", "Barboach"))
        self.pokemon.setItemText(340, _translate("MainWindow", "Whiscash"))
        self.pokemon.setItemText(341, _translate("MainWindow", "Corphish"))
        self.pokemon.setItemText(342, _translate("MainWindow", "Crawdaunt"))
        self.pokemon.setItemText(343, _translate("MainWindow", "Baltoy"))
        self.pokemon.setItemText(344, _translate("MainWindow", "Claydol"))
        self.pokemon.setItemText(345, _translate("MainWindow", "Lileep"))
        self.pokemon.setItemText(346, _translate("MainWindow", "Cradily"))
        self.pokemon.setItemText(347, _translate("MainWindow", "Anorith"))
        self.pokemon.setItemText(348, _translate("MainWindow", "Armaldo"))
        self.pokemon.setItemText(349, _translate("MainWindow", "Feebas"))
        self.pokemon.setItemText(350, _translate("MainWindow", "Milotic"))
        self.pokemon.setItemText(351, _translate("MainWindow", "Castform"))
        self.pokemon.setItemText(352, _translate("MainWindow", "Kecleon"))
        self.pokemon.setItemText(353, _translate("MainWindow", "Shuppet"))
        self.pokemon.setItemText(354, _translate("MainWindow", "Banette"))
        self.pokemon.setItemText(355, _translate("MainWindow", "Duskull"))
        self.pokemon.setItemText(356, _translate("MainWindow", "Dusclops"))
        self.pokemon.setItemText(357, _translate("MainWindow", "Tropius"))
        self.pokemon.setItemText(358, _translate("MainWindow", "Chimecho"))
        self.pokemon.setItemText(359, _translate("MainWindow", "Absol"))
        self.pokemon.setItemText(360, _translate("MainWindow", "Wynaut"))
        self.pokemon.setItemText(361, _translate("MainWindow", "Snorunt"))
        self.pokemon.setItemText(362, _translate("MainWindow", "Glalie"))
        self.pokemon.setItemText(363, _translate("MainWindow", "Spheal"))
        self.pokemon.setItemText(364, _translate("MainWindow", "Sealeo"))
        self.pokemon.setItemText(365, _translate("MainWindow", "Walrein"))
        self.pokemon.setItemText(366, _translate("MainWindow", "Clamperl"))
        self.pokemon.setItemText(367, _translate("MainWindow", "Huntail"))
        self.pokemon.setItemText(368, _translate("MainWindow", "Gorebyss"))
        self.pokemon.setItemText(369, _translate("MainWindow", "Relicanth"))
        self.pokemon.setItemText(370, _translate("MainWindow", "Luvdisc"))
        self.pokemon.setItemText(371, _translate("MainWindow", "Bagon"))
        self.pokemon.setItemText(372, _translate("MainWindow", "Shelgon"))
        self.pokemon.setItemText(373, _translate("MainWindow", "Salamence"))
        self.pokemon.setItemText(374, _translate("MainWindow", "Beldum"))
        self.pokemon.setItemText(375, _translate("MainWindow", "Metang"))
        self.pokemon.setItemText(376, _translate("MainWindow", "Metagross"))
        self.pokemon.setItemText(377, _translate("MainWindow", "Regirock"))
        self.pokemon.setItemText(378, _translate("MainWindow", "Regice"))
        self.pokemon.setItemText(379, _translate("MainWindow", "Registeel"))
        self.pokemon.setItemText(380, _translate("MainWindow", "Latias"))
        self.pokemon.setItemText(381, _translate("MainWindow", "Latios"))
        self.pokemon.setItemText(382, _translate("MainWindow", "Kyogre"))
        self.pokemon.setItemText(383, _translate("MainWindow", "Groudon"))
        self.pokemon.setItemText(384, _translate("MainWindow", "Rayquaza"))
        self.pokemon.setItemText(385, _translate("MainWindow", "Jirachi"))
        self.pokemon.setItemText(386, _translate("MainWindow", "Deoxys"))
        self.pokemon.setItemText(387, _translate("MainWindow", "Turtwig"))
        self.pokemon.setItemText(388, _translate("MainWindow", "Grotle"))
        self.pokemon.setItemText(389, _translate("MainWindow", "Torterra"))
        self.pokemon.setItemText(390, _translate("MainWindow", "Chimchar"))
        self.pokemon.setItemText(391, _translate("MainWindow", "Monferno"))
        self.pokemon.setItemText(392, _translate("MainWindow", "Infernape"))
        self.pokemon.setItemText(393, _translate("MainWindow", "Piplup"))
        self.pokemon.setItemText(394, _translate("MainWindow", "Prinplup"))
        self.pokemon.setItemText(395, _translate("MainWindow", "Empoleon"))
        self.pokemon.setItemText(396, _translate("MainWindow", "Starly"))
        self.pokemon.setItemText(397, _translate("MainWindow", "Staravia"))
        self.pokemon.setItemText(398, _translate("MainWindow", "Staraptor"))
        self.pokemon.setItemText(399, _translate("MainWindow", "Bidoof"))
        self.pokemon.setItemText(400, _translate("MainWindow", "Bibarel"))
        self.pokemon.setItemText(401, _translate("MainWindow", "Kricketot"))
        self.pokemon.setItemText(402, _translate("MainWindow", "Kricketune"))
        self.pokemon.setItemText(403, _translate("MainWindow", "Shinx"))
        self.pokemon.setItemText(404, _translate("MainWindow", "Luxio"))
        self.pokemon.setItemText(405, _translate("MainWindow", "Luxray"))
        self.pokemon.setItemText(406, _translate("MainWindow", "Budew"))
        self.pokemon.setItemText(407, _translate("MainWindow", "Roserade"))
        self.pokemon.setItemText(408, _translate("MainWindow", "Cranidos"))
        self.pokemon.setItemText(409, _translate("MainWindow", "Rampardos"))
        self.pokemon.setItemText(410, _translate("MainWindow", "Shieldon"))
        self.pokemon.setItemText(411, _translate("MainWindow", "Bastiodon"))
        self.pokemon.setItemText(412, _translate("MainWindow", "Burmy"))
        self.pokemon.setItemText(413, _translate("MainWindow", "Wormadam"))
        self.pokemon.setItemText(414, _translate("MainWindow", "Mothim"))
        self.pokemon.setItemText(415, _translate("MainWindow", "Combee"))
        self.pokemon.setItemText(416, _translate("MainWindow", "Vespiquen"))
        self.pokemon.setItemText(417, _translate("MainWindow", "Pachirisu"))
        self.pokemon.setItemText(418, _translate("MainWindow", "Buizel"))
        self.pokemon.setItemText(419, _translate("MainWindow", "Floatzel"))
        self.pokemon.setItemText(420, _translate("MainWindow", "Cherubi"))
        self.pokemon.setItemText(421, _translate("MainWindow", "Cherrim"))
        self.pokemon.setItemText(422, _translate("MainWindow", "Shellos"))
        self.pokemon.setItemText(423, _translate("MainWindow", "Gastrodon"))
        self.pokemon.setItemText(424, _translate("MainWindow", "Ambipom"))
        self.pokemon.setItemText(425, _translate("MainWindow", "Drifloon"))
        self.pokemon.setItemText(426, _translate("MainWindow", "Drifblim"))
        self.pokemon.setItemText(427, _translate("MainWindow", "Buneary"))
        self.pokemon.setItemText(428, _translate("MainWindow", "Lopunny"))
        self.pokemon.setItemText(429, _translate("MainWindow", "Mismagius"))
        self.pokemon.setItemText(430, _translate("MainWindow", "Honchkrow"))
        self.pokemon.setItemText(431, _translate("MainWindow", "Glameow"))
        self.pokemon.setItemText(432, _translate("MainWindow", "Purugly"))
        self.pokemon.setItemText(433, _translate("MainWindow", "Chingling"))
        self.pokemon.setItemText(434, _translate("MainWindow", "Stunky"))
        self.pokemon.setItemText(435, _translate("MainWindow", "Skuntank"))
        self.pokemon.setItemText(436, _translate("MainWindow", "Bronzor"))
        self.pokemon.setItemText(437, _translate("MainWindow", "Bronzong"))
        self.pokemon.setItemText(438, _translate("MainWindow", "Bonsly"))
        self.pokemon.setItemText(439, _translate("MainWindow", "Mime Jr."))
        self.pokemon.setItemText(440, _translate("MainWindow", "Happiny"))
        self.pokemon.setItemText(441, _translate("MainWindow", "Chatot"))
        self.pokemon.setItemText(442, _translate("MainWindow", "Spiritomb"))
        self.pokemon.setItemText(443, _translate("MainWindow", "Gible"))
        self.pokemon.setItemText(444, _translate("MainWindow", "Gabite"))
        self.pokemon.setItemText(445, _translate("MainWindow", "Garchomp"))
        self.pokemon.setItemText(446, _translate("MainWindow", "Munchlax"))
        self.pokemon.setItemText(447, _translate("MainWindow", "Riolu"))
        self.pokemon.setItemText(448, _translate("MainWindow", "Lucario"))
        self.pokemon.setItemText(449, _translate("MainWindow", "Hippopotas"))
        self.pokemon.setItemText(450, _translate("MainWindow", "Hippowdon"))
        self.pokemon.setItemText(451, _translate("MainWindow", "Skorupi"))
        self.pokemon.setItemText(452, _translate("MainWindow", "Drapion"))
        self.pokemon.setItemText(453, _translate("MainWindow", "Croagunk"))
        self.pokemon.setItemText(454, _translate("MainWindow", "Toxicroak"))
        self.pokemon.setItemText(455, _translate("MainWindow", "Carnivine"))
        self.pokemon.setItemText(456, _translate("MainWindow", "Finneon"))
        self.pokemon.setItemText(457, _translate("MainWindow", "Lumineon"))
        self.pokemon.setItemText(458, _translate("MainWindow", "Mantyke"))
        self.pokemon.setItemText(459, _translate("MainWindow", "Snover"))
        self.pokemon.setItemText(460, _translate("MainWindow", "Abomasnow"))
        self.pokemon.setItemText(461, _translate("MainWindow", "Weavile"))
        self.pokemon.setItemText(462, _translate("MainWindow", "Magnezone"))
        self.pokemon.setItemText(463, _translate("MainWindow", "Lickilicky"))
        self.pokemon.setItemText(464, _translate("MainWindow", "Rhyperior"))
        self.pokemon.setItemText(465, _translate("MainWindow", "Tangrowth"))
        self.pokemon.setItemText(466, _translate("MainWindow", "Electivire"))
        self.pokemon.setItemText(467, _translate("MainWindow", "Magmortar"))
        self.pokemon.setItemText(468, _translate("MainWindow", "Togekiss"))
        self.pokemon.setItemText(469, _translate("MainWindow", "Yanmega"))
        self.pokemon.setItemText(470, _translate("MainWindow", "Leafeon"))
        self.pokemon.setItemText(471, _translate("MainWindow", "Glaceon"))
        self.pokemon.setItemText(472, _translate("MainWindow", "Gliscor"))
        self.pokemon.setItemText(473, _translate("MainWindow", "Mamoswine"))
        self.pokemon.setItemText(474, _translate("MainWindow", "Porygon-Z"))
        self.pokemon.setItemText(475, _translate("MainWindow", "Gallade"))
        self.pokemon.setItemText(476, _translate("MainWindow", "Probopass"))
        self.pokemon.setItemText(477, _translate("MainWindow", "Dusknoir"))
        self.pokemon.setItemText(478, _translate("MainWindow", "Froslass"))
        self.pokemon.setItemText(479, _translate("MainWindow", "Rotom"))
        self.pokemon.setItemText(480, _translate("MainWindow", "Uxie"))
        self.pokemon.setItemText(481, _translate("MainWindow", "Mesprit"))
        self.pokemon.setItemText(482, _translate("MainWindow", "Azelf"))
        self.pokemon.setItemText(483, _translate("MainWindow", "Dialga"))
        self.pokemon.setItemText(484, _translate("MainWindow", "Palkia"))
        self.pokemon.setItemText(485, _translate("MainWindow", "Heatran"))
        self.pokemon.setItemText(486, _translate("MainWindow", "Regigigas"))
        self.pokemon.setItemText(487, _translate("MainWindow", "Giratina"))
        self.pokemon.setItemText(488, _translate("MainWindow", "Cresselia"))
        self.pokemon.setItemText(489, _translate("MainWindow", "Phione"))
        self.pokemon.setItemText(490, _translate("MainWindow", "Manaphy"))
        self.pokemon.setItemText(491, _translate("MainWindow", "Darkrai"))
        self.pokemon.setItemText(492, _translate("MainWindow", "Shaymin"))
        self.pokemon.setItemText(493, _translate("MainWindow", "Arceus"))
        self.pokemon.setItemText(494, _translate("MainWindow", "Victini"))
        self.pokemon.setItemText(495, _translate("MainWindow", "Snivy"))
        self.pokemon.setItemText(496, _translate("MainWindow", "Servine"))
        self.pokemon.setItemText(497, _translate("MainWindow", "Serperior"))
        self.pokemon.setItemText(498, _translate("MainWindow", "Tepig"))
        self.pokemon.setItemText(499, _translate("MainWindow", "Pignite"))
        self.pokemon.setItemText(500, _translate("MainWindow", "Emboar"))
        self.pokemon.setItemText(501, _translate("MainWindow", "Oshawott"))
        self.pokemon.setItemText(502, _translate("MainWindow", "Dewott"))
        self.pokemon.setItemText(503, _translate("MainWindow", "Samurott"))
        self.pokemon.setItemText(504, _translate("MainWindow", "Patrat"))
        self.pokemon.setItemText(505, _translate("MainWindow", "Watchog"))
        self.pokemon.setItemText(506, _translate("MainWindow", "Lillipup"))
        self.pokemon.setItemText(507, _translate("MainWindow", "Herdier"))
        self.pokemon.setItemText(508, _translate("MainWindow", "Stoutland"))
        self.pokemon.setItemText(509, _translate("MainWindow", "Purrloin"))
        self.pokemon.setItemText(510, _translate("MainWindow", "Liepard"))
        self.pokemon.setItemText(511, _translate("MainWindow", "Pansage"))
        self.pokemon.setItemText(512, _translate("MainWindow", "Simisage"))
        self.pokemon.setItemText(513, _translate("MainWindow", "Pansear"))
        self.pokemon.setItemText(514, _translate("MainWindow", "Simisear"))
        self.pokemon.setItemText(515, _translate("MainWindow", "Panpour"))
        self.pokemon.setItemText(516, _translate("MainWindow", "Simipour"))
        self.pokemon.setItemText(517, _translate("MainWindow", "Munna"))
        self.pokemon.setItemText(518, _translate("MainWindow", "Musharna"))
        self.pokemon.setItemText(519, _translate("MainWindow", "Pidove"))
        self.pokemon.setItemText(520, _translate("MainWindow", "Tranquill"))
        self.pokemon.setItemText(521, _translate("MainWindow", "Unfezant"))
        self.pokemon.setItemText(522, _translate("MainWindow", "Blitzle"))
        self.pokemon.setItemText(523, _translate("MainWindow", "Zebstrika"))
        self.pokemon.setItemText(524, _translate("MainWindow", "Roggenrola"))
        self.pokemon.setItemText(525, _translate("MainWindow", "Boldore"))
        self.pokemon.setItemText(526, _translate("MainWindow", "Gigalith"))
        self.pokemon.setItemText(527, _translate("MainWindow", "Woobat"))
        self.pokemon.setItemText(528, _translate("MainWindow", "Swoobat"))
        self.pokemon.setItemText(529, _translate("MainWindow", "Drilbur"))
        self.pokemon.setItemText(530, _translate("MainWindow", "Excadrill"))
        self.pokemon.setItemText(531, _translate("MainWindow", "Audino"))
        self.pokemon.setItemText(532, _translate("MainWindow", "Timburr"))
        self.pokemon.setItemText(533, _translate("MainWindow", "Gurdurr"))
        self.pokemon.setItemText(534, _translate("MainWindow", "Conkeldurr"))
        self.pokemon.setItemText(535, _translate("MainWindow", "Tympole"))
        self.pokemon.setItemText(536, _translate("MainWindow", "Palpitoad"))
        self.pokemon.setItemText(537, _translate("MainWindow", "Seismitoad"))
        self.pokemon.setItemText(538, _translate("MainWindow", "Throh"))
        self.pokemon.setItemText(539, _translate("MainWindow", "Sawk"))
        self.pokemon.setItemText(540, _translate("MainWindow", "Sewaddle"))
        self.pokemon.setItemText(541, _translate("MainWindow", "Swadloon"))
        self.pokemon.setItemText(542, _translate("MainWindow", "Leavanny"))
        self.pokemon.setItemText(543, _translate("MainWindow", "Venipede"))
        self.pokemon.setItemText(544, _translate("MainWindow", "Whirlipede"))
        self.pokemon.setItemText(545, _translate("MainWindow", "Scolipede"))
        self.pokemon.setItemText(546, _translate("MainWindow", "Cottonee"))
        self.pokemon.setItemText(547, _translate("MainWindow", "Whimsicott"))
        self.pokemon.setItemText(548, _translate("MainWindow", "Petilil"))
        self.pokemon.setItemText(549, _translate("MainWindow", "Lilligant"))
        self.pokemon.setItemText(550, _translate("MainWindow", "Basculin"))
        self.pokemon.setItemText(551, _translate("MainWindow", "Sandile"))
        self.pokemon.setItemText(552, _translate("MainWindow", "Krokorok"))
        self.pokemon.setItemText(553, _translate("MainWindow", "Krookodile"))
        self.pokemon.setItemText(554, _translate("MainWindow", "Darumaka"))
        self.pokemon.setItemText(555, _translate("MainWindow", "Darmanitan"))
        self.pokemon.setItemText(556, _translate("MainWindow", "Maractus"))
        self.pokemon.setItemText(557, _translate("MainWindow", "Dwebble"))
        self.pokemon.setItemText(558, _translate("MainWindow", "Crustle"))
        self.pokemon.setItemText(559, _translate("MainWindow", "Scraggy"))
        self.pokemon.setItemText(560, _translate("MainWindow", "Scrafty"))
        self.pokemon.setItemText(561, _translate("MainWindow", "Sigilyph"))
        self.pokemon.setItemText(562, _translate("MainWindow", "Yamask"))
        self.pokemon.setItemText(563, _translate("MainWindow", "Cofagrigus"))
        self.pokemon.setItemText(564, _translate("MainWindow", "Tirtouga"))
        self.pokemon.setItemText(565, _translate("MainWindow", "Carracosta"))
        self.pokemon.setItemText(566, _translate("MainWindow", "Archen"))
        self.pokemon.setItemText(567, _translate("MainWindow", "Archeops"))
        self.pokemon.setItemText(568, _translate("MainWindow", "Trubbish"))
        self.pokemon.setItemText(569, _translate("MainWindow", "Garbodor"))
        self.pokemon.setItemText(570, _translate("MainWindow", "Zorua"))
        self.pokemon.setItemText(571, _translate("MainWindow", "Zoroark"))
        self.pokemon.setItemText(572, _translate("MainWindow", "Minccino"))
        self.pokemon.setItemText(573, _translate("MainWindow", "Cinccino"))
        self.pokemon.setItemText(574, _translate("MainWindow", "Gothita"))
        self.pokemon.setItemText(575, _translate("MainWindow", "Gothorita"))
        self.pokemon.setItemText(576, _translate("MainWindow", "Gothitelle"))
        self.pokemon.setItemText(577, _translate("MainWindow", "Solosis"))
        self.pokemon.setItemText(578, _translate("MainWindow", "Duosion"))
        self.pokemon.setItemText(579, _translate("MainWindow", "Reuniclus"))
        self.pokemon.setItemText(580, _translate("MainWindow", "Ducklett"))
        self.pokemon.setItemText(581, _translate("MainWindow", "Swanna"))
        self.pokemon.setItemText(582, _translate("MainWindow", "Vanillite"))
        self.pokemon.setItemText(583, _translate("MainWindow", "Vanillish"))
        self.pokemon.setItemText(584, _translate("MainWindow", "Vanilluxe"))
        self.pokemon.setItemText(585, _translate("MainWindow", "Deerling"))
        self.pokemon.setItemText(586, _translate("MainWindow", "Sawsbuck"))
        self.pokemon.setItemText(587, _translate("MainWindow", "Emolga"))
        self.pokemon.setItemText(588, _translate("MainWindow", "Karrablast"))
        self.pokemon.setItemText(589, _translate("MainWindow", "Escavalier"))
        self.pokemon.setItemText(590, _translate("MainWindow", "Foongus"))
        self.pokemon.setItemText(591, _translate("MainWindow", "Amoonguss"))
        self.pokemon.setItemText(592, _translate("MainWindow", "Frillish"))
        self.pokemon.setItemText(593, _translate("MainWindow", "Jellicent"))
        self.pokemon.setItemText(594, _translate("MainWindow", "Alomomola"))
        self.pokemon.setItemText(595, _translate("MainWindow", "Joltik"))
        self.pokemon.setItemText(596, _translate("MainWindow", "Galvantula"))
        self.pokemon.setItemText(597, _translate("MainWindow", "Ferroseed"))
        self.pokemon.setItemText(598, _translate("MainWindow", "Ferrothorn"))
        self.pokemon.setItemText(599, _translate("MainWindow", "Klink"))
        self.pokemon.setItemText(600, _translate("MainWindow", "Klang"))
        self.pokemon.setItemText(601, _translate("MainWindow", "Klinklang"))
        self.pokemon.setItemText(602, _translate("MainWindow", "Tynamo"))
        self.pokemon.setItemText(603, _translate("MainWindow", "Eelektrik"))
        self.pokemon.setItemText(604, _translate("MainWindow", "Eelektross"))
        self.pokemon.setItemText(605, _translate("MainWindow", "Elgyem"))
        self.pokemon.setItemText(606, _translate("MainWindow", "Beheeyem"))
        self.pokemon.setItemText(607, _translate("MainWindow", "Litwick"))
        self.pokemon.setItemText(608, _translate("MainWindow", "Lampent"))
        self.pokemon.setItemText(609, _translate("MainWindow", "Chandelure"))
        self.pokemon.setItemText(610, _translate("MainWindow", "Axew"))
        self.pokemon.setItemText(611, _translate("MainWindow", "Fraxure"))
        self.pokemon.setItemText(612, _translate("MainWindow", "Haxorus"))
        self.pokemon.setItemText(613, _translate("MainWindow", "Cubchoo"))
        self.pokemon.setItemText(614, _translate("MainWindow", "Beartic"))
        self.pokemon.setItemText(615, _translate("MainWindow", "Cryogonal"))
        self.pokemon.setItemText(616, _translate("MainWindow", "Shelmet"))
        self.pokemon.setItemText(617, _translate("MainWindow", "Accelgor"))
        self.pokemon.setItemText(618, _translate("MainWindow", "Stunfisk"))
        self.pokemon.setItemText(619, _translate("MainWindow", "Mienfoo"))
        self.pokemon.setItemText(620, _translate("MainWindow", "Mienshao"))
        self.pokemon.setItemText(621, _translate("MainWindow", "Druddigon"))
        self.pokemon.setItemText(622, _translate("MainWindow", "Golett"))
        self.pokemon.setItemText(623, _translate("MainWindow", "Golurk"))
        self.pokemon.setItemText(624, _translate("MainWindow", "Pawniard"))
        self.pokemon.setItemText(625, _translate("MainWindow", "Bisharp"))
        self.pokemon.setItemText(626, _translate("MainWindow", "Bouffalant"))
        self.pokemon.setItemText(627, _translate("MainWindow", "Rufflet"))
        self.pokemon.setItemText(628, _translate("MainWindow", "Braviary"))
        self.pokemon.setItemText(629, _translate("MainWindow", "Vullaby"))
        self.pokemon.setItemText(630, _translate("MainWindow", "Mandibuzz"))
        self.pokemon.setItemText(631, _translate("MainWindow", "Heatmor"))
        self.pokemon.setItemText(632, _translate("MainWindow", "Durant"))
        self.pokemon.setItemText(633, _translate("MainWindow", "Deino"))
        self.pokemon.setItemText(634, _translate("MainWindow", "Zweilous"))
        self.pokemon.setItemText(635, _translate("MainWindow", "Hydreigon"))
        self.pokemon.setItemText(636, _translate("MainWindow", "Larvesta"))
        self.pokemon.setItemText(637, _translate("MainWindow", "Volcarona"))
        self.pokemon.setItemText(638, _translate("MainWindow", "Cobalion"))
        self.pokemon.setItemText(639, _translate("MainWindow", "Terrakion"))
        self.pokemon.setItemText(640, _translate("MainWindow", "Virizion"))
        self.pokemon.setItemText(641, _translate("MainWindow", "Tornadus"))
        self.pokemon.setItemText(642, _translate("MainWindow", "Thundurus"))
        self.pokemon.setItemText(643, _translate("MainWindow", "Reshiram"))
        self.pokemon.setItemText(644, _translate("MainWindow", "Zekrom"))
        self.pokemon.setItemText(645, _translate("MainWindow", "Landorus"))
        self.pokemon.setItemText(646, _translate("MainWindow", "Kyurem"))
        self.pokemon.setItemText(647, _translate("MainWindow", "Keldeo"))
        self.pokemon.setItemText(648, _translate("MainWindow", "Meloetta"))
        self.pokemon.setItemText(649, _translate("MainWindow", "Genesect"))
        self.pokemon.setItemText(650, _translate("MainWindow", "Chespin"))
        self.pokemon.setItemText(651, _translate("MainWindow", "Quilladin"))
        self.pokemon.setItemText(652, _translate("MainWindow", "Chesnaught"))
        self.pokemon.setItemText(653, _translate("MainWindow", "Fennekin"))
        self.pokemon.setItemText(654, _translate("MainWindow", "Braixen"))
        self.pokemon.setItemText(655, _translate("MainWindow", "Delphox"))
        self.pokemon.setItemText(656, _translate("MainWindow", "Froakie"))
        self.pokemon.setItemText(657, _translate("MainWindow", "Frogadier"))
        self.pokemon.setItemText(658, _translate("MainWindow", "Greninja"))
        self.pokemon.setItemText(659, _translate("MainWindow", "Bunnelby"))
        self.pokemon.setItemText(660, _translate("MainWindow", "Diggersby"))
        self.pokemon.setItemText(661, _translate("MainWindow", "Fletchling"))
        self.pokemon.setItemText(662, _translate("MainWindow", "Fletchinder"))
        self.pokemon.setItemText(663, _translate("MainWindow", "Talonflame"))
        self.pokemon.setItemText(664, _translate("MainWindow", "Scatterbug"))
        self.pokemon.setItemText(665, _translate("MainWindow", "Spewpa"))
        self.pokemon.setItemText(666, _translate("MainWindow", "Vivillon"))
        self.pokemon.setItemText(667, _translate("MainWindow", "Litleo"))
        self.pokemon.setItemText(668, _translate("MainWindow", "Pyroar"))
        self.pokemon.setItemText(669, _translate("MainWindow", "Flabébé"))
        self.pokemon.setItemText(670, _translate("MainWindow", "Floette"))
        self.pokemon.setItemText(671, _translate("MainWindow", "Florges"))
        self.pokemon.setItemText(672, _translate("MainWindow", "Skiddo"))
        self.pokemon.setItemText(673, _translate("MainWindow", "Gogoat"))
        self.pokemon.setItemText(674, _translate("MainWindow", "Pancham"))
        self.pokemon.setItemText(675, _translate("MainWindow", "Pangoro"))
        self.pokemon.setItemText(676, _translate("MainWindow", "Furfrou"))
        self.pokemon.setItemText(677, _translate("MainWindow", "Espurr"))
        self.pokemon.setItemText(678, _translate("MainWindow", "Meowstic"))
        self.pokemon.setItemText(679, _translate("MainWindow", "Honedge"))
        self.pokemon.setItemText(680, _translate("MainWindow", "Doublade"))
        self.pokemon.setItemText(681, _translate("MainWindow", "Aegislash"))
        self.pokemon.setItemText(682, _translate("MainWindow", "Spritzee"))
        self.pokemon.setItemText(683, _translate("MainWindow", "Aromatisse"))
        self.pokemon.setItemText(684, _translate("MainWindow", "Swirlix"))
        self.pokemon.setItemText(685, _translate("MainWindow", "Slurpuff"))
        self.pokemon.setItemText(686, _translate("MainWindow", "Inkay"))
        self.pokemon.setItemText(687, _translate("MainWindow", "Malamar"))
        self.pokemon.setItemText(688, _translate("MainWindow", "Binacle"))
        self.pokemon.setItemText(689, _translate("MainWindow", "Barbaracle"))
        self.pokemon.setItemText(690, _translate("MainWindow", "Skrelp"))
        self.pokemon.setItemText(691, _translate("MainWindow", "Dragalge"))
        self.pokemon.setItemText(692, _translate("MainWindow", "Clauncher"))
        self.pokemon.setItemText(693, _translate("MainWindow", "Clawitzer"))
        self.pokemon.setItemText(694, _translate("MainWindow", "Helioptile"))
        self.pokemon.setItemText(695, _translate("MainWindow", "Heliolisk"))
        self.pokemon.setItemText(696, _translate("MainWindow", "Tyrunt"))
        self.pokemon.setItemText(697, _translate("MainWindow", "Tyrantrum"))
        self.pokemon.setItemText(698, _translate("MainWindow", "Amaura"))
        self.pokemon.setItemText(699, _translate("MainWindow", "Aurorus"))
        self.pokemon.setItemText(700, _translate("MainWindow", "Sylveon"))
        self.pokemon.setItemText(701, _translate("MainWindow", "Hawlucha"))
        self.pokemon.setItemText(702, _translate("MainWindow", "Dedenne"))
        self.pokemon.setItemText(703, _translate("MainWindow", "Carbink"))
        self.pokemon.setItemText(704, _translate("MainWindow", "Goomy"))
        self.pokemon.setItemText(705, _translate("MainWindow", "Sliggoo"))
        self.pokemon.setItemText(706, _translate("MainWindow", "Goodra"))
        self.pokemon.setItemText(707, _translate("MainWindow", "Klefki"))
        self.pokemon.setItemText(708, _translate("MainWindow", "Phantump"))
        self.pokemon.setItemText(709, _translate("MainWindow", "Trevenant"))
        self.pokemon.setItemText(710, _translate("MainWindow", "Pumpkaboo"))
        self.pokemon.setItemText(711, _translate("MainWindow", "Gourgeist"))
        self.pokemon.setItemText(712, _translate("MainWindow", "Bergmite"))
        self.pokemon.setItemText(713, _translate("MainWindow", "Avalugg"))
        self.pokemon.setItemText(714, _translate("MainWindow", "Noibat"))
        self.pokemon.setItemText(715, _translate("MainWindow", "Noivern"))
        self.pokemon.setItemText(716, _translate("MainWindow", "Xerneas"))
        self.pokemon.setItemText(717, _translate("MainWindow", "Yveltal"))
        self.pokemon.setItemText(718, _translate("MainWindow", "Zygarde"))
        self.pokemon.setItemText(719, _translate("MainWindow", "Diancie"))
        self.pokemon.setItemText(720, _translate("MainWindow", "Hoopa"))
        self.pokemon.setItemText(721, _translate("MainWindow", "Volcanion"))
        self.pokemon.setItemText(722, _translate("MainWindow", "Rowlet"))
        self.pokemon.setItemText(723, _translate("MainWindow", "Dartrix"))
        self.pokemon.setItemText(724, _translate("MainWindow", "Decidueye"))
        self.pokemon.setItemText(725, _translate("MainWindow", "Litten"))
        self.pokemon.setItemText(726, _translate("MainWindow", "Torracat"))
        self.pokemon.setItemText(727, _translate("MainWindow", "Incineroar"))
        self.pokemon.setItemText(728, _translate("MainWindow", "Popplio"))
        self.pokemon.setItemText(729, _translate("MainWindow", "Brionne"))
        self.pokemon.setItemText(730, _translate("MainWindow", "Primarina"))
        self.pokemon.setItemText(731, _translate("MainWindow", "Pikipek"))
        self.pokemon.setItemText(732, _translate("MainWindow", "Trumbeak"))
        self.pokemon.setItemText(733, _translate("MainWindow", "Toucannon"))
        self.pokemon.setItemText(734, _translate("MainWindow", "Yungoos"))
        self.pokemon.setItemText(735, _translate("MainWindow", "Gumshoos"))
        self.pokemon.setItemText(736, _translate("MainWindow", "Grubbin"))
        self.pokemon.setItemText(737, _translate("MainWindow", "Charjabug"))
        self.pokemon.setItemText(738, _translate("MainWindow", "Vikavolt"))
        self.pokemon.setItemText(739, _translate("MainWindow", "Crabrawler"))
        self.pokemon.setItemText(740, _translate("MainWindow", "Crabominable"))
        self.pokemon.setItemText(741, _translate("MainWindow", "Oricorio"))
        self.pokemon.setItemText(742, _translate("MainWindow", "Cutiefly"))
        self.pokemon.setItemText(743, _translate("MainWindow", "Ribombee"))
        self.pokemon.setItemText(744, _translate("MainWindow", "Rockruff"))
        self.pokemon.setItemText(745, _translate("MainWindow", "Lycanroc"))
        self.pokemon.setItemText(746, _translate("MainWindow", "Wishiwashi"))
        self.pokemon.setItemText(747, _translate("MainWindow", "Mareanie"))
        self.pokemon.setItemText(748, _translate("MainWindow", "Toxapex"))
        self.pokemon.setItemText(749, _translate("MainWindow", "Mudbray"))
        self.pokemon.setItemText(750, _translate("MainWindow", "Mudsdale"))
        self.pokemon.setItemText(751, _translate("MainWindow", "Dewpider"))
        self.pokemon.setItemText(752, _translate("MainWindow", "Araquanid"))
        self.pokemon.setItemText(753, _translate("MainWindow", "Fomantis"))
        self.pokemon.setItemText(754, _translate("MainWindow", "Lurantis"))
        self.pokemon.setItemText(755, _translate("MainWindow", "Morelull"))
        self.pokemon.setItemText(756, _translate("MainWindow", "Shiinotic"))
        self.pokemon.setItemText(757, _translate("MainWindow", "Salandit"))
        self.pokemon.setItemText(758, _translate("MainWindow", "Salazzle"))
        self.pokemon.setItemText(759, _translate("MainWindow", "Stufful"))
        self.pokemon.setItemText(760, _translate("MainWindow", "Bewear"))
        self.pokemon.setItemText(761, _translate("MainWindow", "Bounsweet"))
        self.pokemon.setItemText(762, _translate("MainWindow", "Steenee"))
        self.pokemon.setItemText(763, _translate("MainWindow", "Tsareena"))
        self.pokemon.setItemText(764, _translate("MainWindow", "Comfey"))
        self.pokemon.setItemText(765, _translate("MainWindow", "Oranguru"))
        self.pokemon.setItemText(766, _translate("MainWindow", "Passimian"))
        self.pokemon.setItemText(767, _translate("MainWindow", "Wimpod"))
        self.pokemon.setItemText(768, _translate("MainWindow", "Golisopod"))
        self.pokemon.setItemText(769, _translate("MainWindow", "Sandygast"))
        self.pokemon.setItemText(770, _translate("MainWindow", "Palossand"))
        self.pokemon.setItemText(771, _translate("MainWindow", "Pyukumuku"))
        self.pokemon.setItemText(772, _translate("MainWindow", "Type: Null"))
        self.pokemon.setItemText(773, _translate("MainWindow", "Silvally"))
        self.pokemon.setItemText(774, _translate("MainWindow", "Minior"))
        self.pokemon.setItemText(775, _translate("MainWindow", "Komala"))
        self.pokemon.setItemText(776, _translate("MainWindow", "Turtonator"))
        self.pokemon.setItemText(777, _translate("MainWindow", "Togedemaru"))
        self.pokemon.setItemText(778, _translate("MainWindow", "Mimikyu"))
        self.pokemon.setItemText(779, _translate("MainWindow", "Bruxish"))
        self.pokemon.setItemText(780, _translate("MainWindow", "Drampa"))
        self.pokemon.setItemText(781, _translate("MainWindow", "Dhelmise"))
        self.pokemon.setItemText(782, _translate("MainWindow", "Jangmo-o"))
        self.pokemon.setItemText(783, _translate("MainWindow", "Hakamo-o"))
        self.pokemon.setItemText(784, _translate("MainWindow", "Kommo-o"))
        self.pokemon.setItemText(785, _translate("MainWindow", "Tapu Koko"))
        self.pokemon.setItemText(786, _translate("MainWindow", "Tapu Lele"))
        self.pokemon.setItemText(787, _translate("MainWindow", "Tapu Bulu"))
        self.pokemon.setItemText(788, _translate("MainWindow", "Tapu Fini"))
        self.pokemon.setItemText(789, _translate("MainWindow", "Cosmog"))
        self.pokemon.setItemText(790, _translate("MainWindow", "Cosmoem"))
        self.pokemon.setItemText(791, _translate("MainWindow", "Solgaleo"))
        self.pokemon.setItemText(792, _translate("MainWindow", "Lunala"))
        self.pokemon.setItemText(793, _translate("MainWindow", "Nihilego"))
        self.pokemon.setItemText(794, _translate("MainWindow", "Buzzwole"))
        self.pokemon.setItemText(795, _translate("MainWindow", "Pheromosa"))
        self.pokemon.setItemText(796, _translate("MainWindow", "Xurkitree"))
        self.pokemon.setItemText(797, _translate("MainWindow", "Celesteela"))
        self.pokemon.setItemText(798, _translate("MainWindow", "Kartana"))
        self.pokemon.setItemText(799, _translate("MainWindow", "Guzzlord"))
        self.pokemon.setItemText(800, _translate("MainWindow", "Necrozma"))
        self.pokemon.setItemText(801, _translate("MainWindow", "Magearna"))
        self.pokemon.setItemText(802, _translate("MainWindow", "Marshadow"))
        self.pokemon.setItemText(803, _translate("MainWindow", "Poipole"))
        self.pokemon.setItemText(804, _translate("MainWindow", "Naganadel"))
        self.pokemon.setItemText(805, _translate("MainWindow", "Stakataka"))
        self.pokemon.setItemText(806, _translate("MainWindow", "Blacephalon"))
        self.pokemon.setItemText(807, _translate("MainWindow", "Zeraora"))
        self.pokemon.setEditable(True)
        self.tradestatus.setItemText(0, _translate("MainWindow", "Select Trade Status"))
        self.tradestatus.setItemText(1, _translate("MainWindow", "Not Traded"))
        self.tradestatus.setItemText(2, _translate("MainWindow", "Traded Nationally"))
        self.tradestatus.setItemText(3, _translate("MainWindow", "Traded Internationally"))
        self.affection.setItemText(0, _translate("MainWindow", "Select Affection"))
        self.affection.setItemText(1, _translate("MainWindow", "Below 2 Hearts"))
        self.affection.setItemText(2, _translate("MainWindow", "2 Hearts or Above"))
        self.luckyegg.setItemText(0, _translate("MainWindow", "Select Lucky Egg"))
        self.luckyegg.setItemText(1, _translate("MainWindow", "Lucky Egg Equipped"))
        self.luckyegg.setItemText(2, _translate("MainWindow", "Lucky Egg Not Equipped"))

        self.label.setText(_translate("MainWindow", "Starting Level"))
        self.label_2.setText(_translate("MainWindow", "Goal Level"))
        

    def button(self):
        print(str(self.route.currentText()))
        print(str(self.luckyegg.currentText()))
        print(str(self.affection.currentText()))
        print(str(self.tradestatus.currentText()))
        print(str(self.pokemon.currentText()))
        print('Level',str(self.level.value()))
        grind(route_convert(str(self.route.currentText())),
              egg_convert(str(self.luckyegg.currentText())),
              affec_convert(str(self.affection.currentText())),
              stat_convert(str(self.tradestatus.currentText())),
              str(self.pokemon.currentText()),
              self.level.value(),
              self.level_2.value())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

